# config/schemas/prompts.yaml

prompts:
  formatting:
    tagged:
      prompt: |
        You are a data formatter. Convert the following unformatted text into a structured format with tags as shown below:

        Example:
        <id=1>
        <title>Sample Title</title>
        <published_date>2024-09-22</published_date>
        <categories><Category1><Category2></categories>
        <content>
        Sample content here.
        </content>
        </id=1>

        Unformatted Text:
        {raw_text}

        Formatted Text:
    json:
      prompt: |
        You are a data formatter. Convert the following unformatted text into a structured JSON format adhering to the provided schema.

        Schema:
        {json_schema}

        Unformatted Text:
        {raw_text}

        Formatted JSON:
  enrichment:
    enrichment_prompt: |
      Analyze the following legal text and provide the main topic, applicability, a concise title, and relevant categories.

      Text:
      {chunk_text}

      Main Topic:
      Applicability:
      Generated Title:
      Suggested Categories:
